name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Client Image
        run: docker build -t import-export-client ./import-export-client

      - name: Build Server Image
        run: docker build -t import-export-server ./import-export-server